# Generated by Django 6.0 on 2025-12-19 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(choices=[('MEAT', 'MEAT'), ('VEG', 'VEG'), ('DAIRY', 'DAIRY'), ('SAUCE', 'SAUCE'), ('ETC', 'ETC')], default='ETC', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='PUBLIC', max_length=50)),
                ('source_recipe_id', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='')),
                ('cook_time_min', models.IntegerField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('EASY', 'EASY'), ('MID', 'MID'), ('HARD', 'HARD')], default='EASY', max_length=10)),
                ('servings', models.IntegerField(blank=True, null=True)),
                ('cuisine', models.CharField(blank=True, default='', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toss_user_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('nickname', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.JSONField(blank=True, default=dict)),
                ('result_recipe_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_history', to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_type', models.CharField(choices=[('NONE', 'NONE'), ('LOW_CARB', 'LOW_CARB'), ('LOW_SODIUM', 'LOW_SODIUM'), ('HIGH_PROTEIN', 'HIGH_PROTEIN'), ('VEGAN', 'VEGAN')], default='NONE', max_length=20)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('spice_level', models.IntegerField(default=0)),
                ('max_cook_time_min', models.IntegerField(default=20)),
                ('skill_level', models.CharField(choices=[('BEGINNER', 'BEGINNER'), ('MID', 'MID'), ('PRO', 'PRO')], default='BEGINNER', max_length=20)),
                ('servings_default', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_text', models.CharField(blank=True, default='', max_length=50)),
                ('is_optional', models.BooleanField(default=False)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_recipes', to='app.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='app.recipe')),
            ],
            options={
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.IntegerField()),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, default='')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='app.recipe')),
            ],
            options={
                'ordering': ['step_no'],
                'unique_together': {('recipe', 'step_no')},
            },
        ),
        migrations.CreateModel(
            name='UserPantry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_text', models.CharField(blank=True, default='', max_length=50)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_pantries', to='app.ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to='app.user')),
            ],
            options={
                'unique_together': {('user', 'ingredient')},
            },
        ),
    ]
