# Generated by Django 6.0 on 2026-01-09 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('save', 'save'), ('cook', 'cook'), ('skip', 'skip')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='app.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_actions', to='app.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'action', 'created_at'], name='app_recipea_user_id_c25af3_idx')],
            },
        ),
    ]
