# Generated by Django 6.0 on 2026-01-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usersavedrecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalRecipeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('cache_key', models.CharField(max_length=200, unique=True)),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
