# Generated by Django 6.0 on 2026-01-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_externalrecipecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='external_source',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['external_source', 'external_id'], name='app_recipe_externa_ca6419_idx'),
        ),
    ]
