# Generated by Django 6.0 on 2026-01-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_appsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_url_small',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instruction_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recipe',
            name='raw_ingredients',
            field=models.TextField(blank=True, default=''),
        ),
    ]
