# Generated by Django 6.0 on 2026-01-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_recipe_is_public_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/thumbnails/'),
        ),
        migrations.AddField(
            model_name='recipestep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/steps/'),
        ),
    ]
